import type { Metadata } from "next";
import "@/styles/globals.css";
import { VazirFont } from "constants/localFont";



export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${VazirFont.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
